// Chain identity and Multicall3 check (SPEC sections 10.1, 10.3 and 15).
//
// The chain record `config/chains/<chainId>.json` carries two facts that only a node can settle:
// `networkIdentity.genesisHash` and `networkIdentity.multicall3`. Both are null until an operator verifies
// them against the live chain, and rule CH4 in `scripts/validate_config.ts` fails any chain record that
// still holds a null in either field once a mainnet manifest exists. This script performs that
// verification and prints the fragment to paste, under those two exact field names.
//
// What it does, in order:
//
//   1. `eth_chainId`                          must equal --chain-id;
//   2. `eth_getBlockByNumber("0x0")`          the genesis hash, compared with the record;
//   3. `eth_getCode(--multicall3)`            must be non-empty; its keccak256 is printed as an identity
//                                             fingerprint the operator can compare across chains;
//   4. `eth_blockNumber`                      the head, read before and after the calls;
//   5. `eth_call getBlockNumber()`            through the given address, must land inside that window;
//   6. `eth_call aggregate3([getBlockNumber(), getChainId()])`
//                                             both items must succeed, the block number must land inside
//                                             the same window and the chain id must equal --chain-id.
//
// Rules this file obeys:
//
//   - No address is hardcoded. The Multicall3 address is an operator argument, taken from the source page
//     on the day (brief ground rule; SPEC section 10.3 does not name one).
//   - Read-only. It never writes `config/chains/<id>.json`; --write is refused with a message.
//   - The RPC URL is a credential (operator endpoints carry the key in the path or the query), so it is
//     replaced by `<rpc>` in every line this script prints, including provider error messages.
//   - Runs under plain `node scripts/check_chain_record.ts` on Node 24 (pinned in .nvmrc) and Node 25:
//     inside the erasable TypeScript subset, no enums, no namespaces, no parameter properties.
//
// Usage:
//   node scripts/check_chain_record.ts --rpc-url <url> --chain-id <id> --multicall3 <address>
//                                      [--config-root <dir>] [--head-slack <blocks>]

import {readFileSync} from "node:fs";
import {dirname, join, resolve} from "node:path";
import {pathToFileURL} from "node:url";

const SCRIPT_DIR: string = import.meta.dirname;
const REPO_ROOT: string = dirname(SCRIPT_DIR);

// ---------------------------------------------------------------------------
// keccak256 (FIPS 202), used for the function selectors and the code hash
// ---------------------------------------------------------------------------
//
// The repository root has no ethers dependency (only the workspace packages do), and a selector copied from
// memory is exactly the kind of unverified constant this script exists to eliminate. So the selectors are
// derived from their signatures here, and `check_chain_record.test.ts` pins the derived values against the
// method identifiers Foundry generates for forge-std's `IMulticall3`.

const MASK64: bigint = (1n << 64n) - 1n;

function rotl64(value: bigint, shift: number): bigint {
  const n = BigInt(shift);
  return ((value << n) | (value >> (64n - n))) & MASK64;
}

/** The 24 round constants, generated by the FIPS 202 Algorithm 5 LFSR rather than tabulated. */
const ROUND_CONSTANTS: readonly bigint[] = (() => {
  const constants: bigint[] = [];
  let lfsr = 0x01;
  for (let round = 0; round < 24; round += 1) {
    let rc = 0n;
    for (let j = 0; j < 7; j += 1) {
      const bit = lfsr & 0x01;
      lfsr = (lfsr & 0x80) !== 0 ? ((lfsr << 1) ^ 0x71) & 0xff : (lfsr << 1) & 0xff;
      if (bit !== 0) rc ^= 1n << BigInt((1 << j) - 1);
    }
    constants.push(rc);
  }
  return constants;
})();

/** The rho rotation offsets paired with the pi lane order, generated from the (x, y) walk of FIPS 202. */
const RHO_PI: readonly {lane: number; shift: number}[] = (() => {
  const steps: {lane: number; shift: number}[] = [];
  let x = 1;
  let y = 0;
  for (let t = 0; t < 24; t += 1) {
    const nextX = y;
    const nextY = (2 * x + 3 * y) % 5;
    x = nextX;
    y = nextY;
    steps.push({lane: x + 5 * y, shift: (((t + 1) * (t + 2)) / 2) % 64});
  }
  return steps;
})();

function keccakF1600(lanes: bigint[]): void {
  for (const rc of ROUND_CONSTANTS) {
    const column: bigint[] = [];
    for (let x = 0; x < 5; x += 1) {
      column.push(lanes[x] ^ lanes[x + 5] ^ lanes[x + 10] ^ lanes[x + 15] ^ lanes[x + 20]);
    }
    for (let x = 0; x < 5; x += 1) {
      const d = column[(x + 4) % 5] ^ rotl64(column[(x + 1) % 5], 1);
      for (let y = 0; y < 25; y += 5) lanes[x + y] ^= d;
    }
    let current = lanes[1];
    for (const step of RHO_PI) {
      const held = lanes[step.lane];
      lanes[step.lane] = rotl64(current, step.shift);
      current = held;
    }
    for (let y = 0; y < 25; y += 5) {
      const row = [lanes[y], lanes[y + 1], lanes[y + 2], lanes[y + 3], lanes[y + 4]];
      for (let x = 0; x < 5; x += 1) {
        lanes[y + x] = row[x] ^ (~row[(x + 1) % 5] & MASK64 & row[(x + 2) % 5]);
      }
    }
    lanes[0] ^= rc;
  }
}

/** keccak256 of a byte string, as `0x`-prefixed lowercase hex. */
export function keccak256(message: Uint8Array): string {
  const RATE = 136;
  const lanes: bigint[] = new Array(25).fill(0n);
  const padded = new Uint8Array(Math.ceil((message.length + 1) / RATE) * RATE);
  padded.set(message);
  padded[message.length] ^= 0x01;
  padded[padded.length - 1] ^= 0x80;
  for (let block = 0; block < padded.length; block += RATE) {
    for (let i = 0; i < RATE; i += 8) {
      let lane = 0n;
      for (let b = 7; b >= 0; b -= 1) lane = (lane << 8n) | BigInt(padded[block + i + b]);
      lanes[i / 8] ^= lane;
    }
    keccakF1600(lanes);
  }
  let out = "0x";
  for (let i = 0; i < 32; i += 1) {
    const byte = Number((lanes[Math.floor(i / 8)] >> BigInt(8 * (i % 8))) & 0xffn);
    out += byte.toString(16).padStart(2, "0");
  }
  return out;
}

/** The 4-byte selector of a Solidity function signature, derived (never remembered). */
export function selectorOf(signature: string): string {
  return keccak256(new TextEncoder().encode(signature)).slice(0, 10);
}

export const GET_BLOCK_NUMBER: string = selectorOf("getBlockNumber()");
export const GET_CHAIN_ID: string = selectorOf("getChainId()");
export const AGGREGATE3: string = selectorOf("aggregate3((address,bool,bytes)[])");

// ---------------------------------------------------------------------------
// Minimal ABI coding for the one call shape this script needs
// ---------------------------------------------------------------------------

function hexBody(value: string): string {
  return value.startsWith("0x") || value.startsWith("0X") ? value.slice(2) : value;
}

function word(value: bigint): string {
  if (value < 0n) throw new Error("only non-negative words are encoded here");
  return value.toString(16).padStart(64, "0");
}

function wordAt(body: string, byteOffset: number): bigint {
  const start = byteOffset * 2;
  const slice = body.slice(start, start + 64);
  if (slice.length !== 64) throw new Error(`the response ends inside word ${byteOffset / 32}`);
  return BigInt(`0x${slice}`);
}

function toNumber(value: bigint, what: string): number {
  if (value > BigInt(Number.MAX_SAFE_INTEGER)) throw new Error(`${what} is implausibly large: ${value}`);
  return Number(value);
}

/** `aggregate3((address,bool,bytes)[])` calldata for a list of calls, every one with allowFailure true. */
export function encodeAggregate3(calls: readonly {target: string; callData: string}[]): string {
  const tuples = calls.map((call) => {
    const data = hexBody(call.callData);
    const padding = "0".repeat((64 - (data.length % 64)) % 64);
    return (
      word(BigInt(call.target)) + word(1n) + word(0x60n) + word(BigInt(data.length / 2)) + data + padding
    );
  });
  // Offsets are measured from the first word after the array length.
  let cursor = 32 * tuples.length;
  const offsets: string[] = [];
  for (const tuple of tuples) {
    offsets.push(word(BigInt(cursor)));
    cursor += tuple.length / 2;
  }
  return `${AGGREGATE3}${word(0x20n)}${word(BigInt(tuples.length))}${offsets.join("")}${tuples.join("")}`;
}

export type AggregateItem = {success: boolean; returnData: string};

/** Decodes `Result[] (bool success, bytes returnData)`. */
export function decodeAggregate3(raw: string): AggregateItem[] {
  const body = hexBody(raw);
  const arrayAt = toNumber(wordAt(body, 0), "the aggregate3 array offset");
  const count = toNumber(wordAt(body, arrayAt), "the aggregate3 result count");
  const base = arrayAt + 32;
  const items: AggregateItem[] = [];
  for (let i = 0; i < count; i += 1) {
    const at = base + toNumber(wordAt(body, base + 32 * i), "an aggregate3 element offset");
    const success = wordAt(body, at);
    if (success > 1n) throw new Error(`aggregate3 element ${i} has a success flag of ${success}`);
    const dataAt = at + toNumber(wordAt(body, at + 32), "an aggregate3 returnData offset");
    const length = toNumber(wordAt(body, dataAt), "an aggregate3 returnData length");
    const data = body.slice((dataAt + 32) * 2, (dataAt + 32 + length) * 2);
    if (data.length !== length * 2) throw new Error(`aggregate3 element ${i} is truncated`);
    items.push({success: success === 1n, returnData: `0x${data}`});
  }
  return items;
}

// ---------------------------------------------------------------------------
// RPC
// ---------------------------------------------------------------------------

/** One JSON-RPC round trip. Injected by the tests, which never touch a network. */
export type RpcFn = (method: string, params: readonly unknown[]) => Promise<unknown>;

const URL_LIKE = /\bhttps?:\/\/[^\s"'\\]*/gi;

/** Every absolute URL replaced by `<rpc>`: an operator endpoint usually *is* the credential. */
export function redactUrls(value: string): string {
  return value.replace(URL_LIKE, "<rpc>");
}

/** A `fetch`-backed `RpcFn` for one endpoint. Nothing else in this file knows the URL. */
export function httpRpc(url: string, timeoutMs = 20_000): RpcFn {
  let id = 0;
  return async (method, params) => {
    id += 1;
    const response = await fetch(url, {
      method: "POST",
      headers: {"content-type": "application/json"},
      body: JSON.stringify({jsonrpc: "2.0", id, method, params}),
      signal: AbortSignal.timeout(timeoutMs),
    });
    if (!response.ok) {
      throw new Error(`${method} answered HTTP ${response.status} ${response.statusText}`);
    }
    const payload = (await response.json()) as {result?: unknown; error?: {message?: unknown}};
    if (payload.error !== undefined && payload.error !== null) {
      throw new Error(`${method} failed: ${String(payload.error.message ?? "no message")}`);
    }
    return payload.result;
  };
}

// ---------------------------------------------------------------------------
// The check
// ---------------------------------------------------------------------------

export const ADDRESS_RE = /^0x[0-9a-fA-F]{40}$/;
const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";

/** The two `networkIdentity` fields of `config/chains/<id>.json`, as read from disk. */
export type ChainRecordIdentity = {
  /** The record's own `chainId`, so a file named for another chain is caught. */
  chainId: number | null;
  genesisHash: string | null;
  multicall3: string | null;
};

export type CheckInput = {
  chainId: bigint;
  multicall3: string;
  rpc: RpcFn;
  /** Null when no record exists for this chain id; then only the chain is checked. */
  record: ChainRecordIdentity | null;
  /** Display path of the record, for the messages. */
  recordPath: string;
  /** Blocks the head may advance by between the two `eth_blockNumber` reads, before it looks wrong. */
  headSlack?: bigint;
  /** UTC date stamped into the printed fragment. Injected by the tests. */
  today?: string;
};

export type Level = "ok" | "note" | "error";
export type Finding = {code: string; level: Level; message: string};

export type Observed = {
  chainId: bigint | null;
  genesisHash: string | null;
  codeSize: number | null;
  codeHash: string | null;
  headBefore: bigint | null;
  headAfter: bigint | null;
  multicallBlockNumber: bigint | null;
  aggregateBlockNumber: bigint | null;
  aggregateChainId: bigint | null;
};

export type CheckResult = {
  findings: Finding[];
  observed: Observed;
  /** The `networkIdentity` object to paste, or null when the chain could not be read. */
  fragment: string | null;
  ok: boolean;
};

function ok(findings: Finding[], code: string, message: string): void {
  findings.push({code, level: "ok", message});
}
function note(findings: Finding[], code: string, message: string): void {
  findings.push({code, level: "note", message});
}
function bad(findings: Finding[], code: string, message: string): void {
  findings.push({code, level: "error", message});
}

async function quantity(rpc: RpcFn, method: string, params: readonly unknown[]): Promise<bigint> {
  const raw = await rpc(method, params);
  if (typeof raw !== "string" || !/^0x[0-9a-fA-F]+$/.test(raw)) {
    throw new Error(`${method} answered ${JSON.stringify(raw)}, which is not a quantity`);
  }
  return BigInt(raw);
}

function message(error: unknown): string {
  return redactUrls(error instanceof Error ? error.message : String(error));
}

function todayUtc(): string {
  return new Date().toISOString().slice(0, 10);
}

/**
 * Reads the chain, compares it with the record and builds the fragment.
 *
 * Every RPC failure becomes a finding rather than a thrown error, so one unreachable method (an old node
 * without `eth_getCode` at `latest`, say) still leaves the other answers on screen.
 */
export async function checkChainRecord(input: CheckInput): Promise<CheckResult> {
  const findings: Finding[] = [];
  const slack = input.headSlack ?? 8n;
  const observed: Observed = {
    chainId: null,
    genesisHash: null,
    codeSize: null,
    codeHash: null,
    headBefore: null,
    headAfter: null,
    multicallBlockNumber: null,
    aggregateBlockNumber: null,
    aggregateChainId: null,
  };

  if (!ADDRESS_RE.test(input.multicall3)) {
    bad(findings, "C0", `--multicall3 ${JSON.stringify(input.multicall3)} is not an address`);
    return {findings, observed, fragment: null, ok: false};
  }
  const multicall3 = input.multicall3.toLowerCase();
  if (multicall3 === ZERO_ADDRESS) {
    bad(findings, "C0", "--multicall3 is the zero address");
    return {findings, observed, fragment: null, ok: false};
  }

  // 1. chain id
  try {
    observed.chainId = await quantity(input.rpc, "eth_chainId", []);
    if (observed.chainId === input.chainId) {
      ok(findings, "C1", `eth_chainId is ${observed.chainId}, as asked`);
    } else {
      bad(
        findings,
        "C1",
        `eth_chainId is ${observed.chainId} but --chain-id is ${input.chainId}; this endpoint is a ` +
          `different network. Nothing below describes the chain you meant.`,
      );
    }
  } catch (error) {
    bad(findings, "C1", `eth_chainId could not be read: ${message(error)}`);
  }

  // 2. genesis hash
  try {
    const block = await input.rpc("eth_getBlockByNumber", ["0x0", false]);
    const hash = (block as {hash?: unknown} | null)?.hash;
    if (typeof hash !== "string" || !/^0x[0-9a-fA-F]{64}$/.test(hash)) {
      bad(findings, "C2", `the node did not return a block 0 hash (got ${JSON.stringify(hash ?? null)})`);
    } else {
      observed.genesisHash = hash.toLowerCase();
      ok(findings, "C2", `block 0 hash is ${observed.genesisHash}`);
    }
  } catch (error) {
    bad(findings, "C2", `block 0 could not be read: ${message(error)}`);
  }

  // 3. code at the given address
  let hasCode = false;
  try {
    const code = await input.rpc("eth_getCode", [multicall3, "latest"]);
    if (typeof code !== "string" || !/^0x([0-9a-fA-F]{2})*$/.test(code)) {
      bad(findings, "C3", `eth_getCode answered ${JSON.stringify(code)}, which is not bytecode`);
    } else if (code === "0x") {
      bad(
        findings,
        "C3",
        `there is no code at ${multicall3} on chain ${observed.chainId ?? "?"}. Multicall3 is not ` +
          `deployed at that address here, or the address is wrong; do not record it.`,
      );
    } else {
      const bytes = Uint8Array.from(
        (hexBody(code).match(/../g) ?? []).map((pair) => Number.parseInt(pair, 16)),
      );
      hasCode = true;
      observed.codeSize = bytes.length;
      observed.codeHash = keccak256(bytes);
      ok(findings, "C3", `${bytes.length} bytes of code at ${multicall3}, keccak256 ${observed.codeHash}`);
    }
  } catch (error) {
    bad(findings, "C3", `eth_getCode could not be read: ${message(error)}`);
  }

  // 4 to 6. the head window, getBlockNumber() and aggregate3 through the address
  if (hasCode) {
    try {
      observed.headBefore = await quantity(input.rpc, "eth_blockNumber", []);
      const direct = await input.rpc("eth_call", [{to: multicall3, data: GET_BLOCK_NUMBER}, "latest"]);
      if (typeof direct !== "string" || hexBody(direct).length !== 64) {
        bad(findings, "C4", `getBlockNumber() answered ${JSON.stringify(direct)}, not one uint256`);
      } else {
        observed.multicallBlockNumber = BigInt(direct);
      }

      const aggregateCall = encodeAggregate3([
        {target: multicall3, callData: GET_BLOCK_NUMBER},
        {target: multicall3, callData: GET_CHAIN_ID},
      ]);
      const aggregated = await input.rpc("eth_call", [{to: multicall3, data: aggregateCall}, "latest"]);
      observed.headAfter = await quantity(input.rpc, "eth_blockNumber", []);

      if (typeof aggregated !== "string") {
        bad(findings, "C5", `aggregate3 answered ${JSON.stringify(aggregated)}`);
      } else {
        // Null, not `[]`: a decode failure and a well-formed but *empty* `Result[]` are different facts and
        // only the first has already produced a finding above. Defaulting to an empty list made the two
        // indistinguishable, and an empty answer then fell through both branches below - C5 stayed silent
        // and the fragment printed as though Multicall3 had confirmed the chain for two calls it never
        // answered. Every non-null length other than 2 is a failure, zero included.
        let items: AggregateItem[] | null = null;
        try {
          items = decodeAggregate3(aggregated);
        } catch (error) {
          bad(findings, "C5", `aggregate3 did not decode as Result[]: ${message(error)}`);
        }
        if (items !== null && items.length === 2) {
          const [blockItem, chainItem] = items;
          if (!blockItem.success || !chainItem.success) {
            bad(
              findings,
              "C5",
              `aggregate3 reported failure for ${!blockItem.success ? "getBlockNumber()" : "getChainId()"}` +
                `; the contract at ${multicall3} does not behave like Multicall3`,
            );
          } else if (
            hexBody(blockItem.returnData).length !== 64 ||
            hexBody(chainItem.returnData).length !== 64
          ) {
            bad(findings, "C5", "aggregate3 returned items that are not uint256 words");
          } else {
            observed.aggregateBlockNumber = BigInt(blockItem.returnData);
            observed.aggregateChainId = BigInt(chainItem.returnData);
          }
        } else if (items !== null) {
          bad(findings, "C5", `aggregate3 returned ${items.length} results for 2 calls`);
        }
      }
    } catch (error) {
      bad(findings, "C4", `the Multicall3 calls could not be made: ${message(error)}`);
    }

    const before = observed.headBefore;
    const after = observed.headAfter;
    const window = (value: bigint | null, code: string, what: string): void => {
      if (value === null || before === null || after === null) return;
      if (value >= before && value <= after + slack) {
        ok(findings, code, `${what} is ${value}, inside the head window ${before}..${after}`);
      } else {
        bad(
          findings,
          code,
          `${what} is ${value} but eth_blockNumber moved ${before} -> ${after} around the call; the ` +
            `contract at ${multicall3} is not answering for this chain's head`,
        );
      }
    };
    window(observed.multicallBlockNumber, "C4", "getBlockNumber()");
    window(observed.aggregateBlockNumber, "C5", "aggregate3 getBlockNumber()");

    if (observed.aggregateChainId !== null) {
      if (observed.aggregateChainId === input.chainId) {
        ok(findings, "C6", `aggregate3 getChainId() is ${observed.aggregateChainId}, as asked`);
      } else {
        bad(
          findings,
          "C6",
          `aggregate3 getChainId() is ${observed.aggregateChainId} but --chain-id is ${input.chainId}`,
        );
      }
    }
  } else {
    note(findings, "C4", "the Multicall3 calls were skipped: there is no code at that address");
  }

  // 7 to 9. the record on disk
  const record = input.record;
  if (record === null) {
    note(findings, "C7", `${input.recordPath} does not exist; nothing on disk to compare`);
  } else {
    if (record.chainId !== null && BigInt(record.chainId) !== input.chainId) {
      bad(
        findings,
        "C7",
        `${input.recordPath} declares chainId ${record.chainId} but --chain-id is ${input.chainId}`,
      );
    }
    const compare = (code: string, field: string, recorded: string | null, seen: string | null): void => {
      if (recorded === null) {
        note(
          findings,
          code,
          `${input.recordPath} networkIdentity.${field} is null; paste the fragment below once the ` +
            `numbers above look right`,
        );
      } else if (seen === null) {
        note(findings, code, `networkIdentity.${field} is recorded as ${recorded}; the chain was not read`);
      } else if (recorded.toLowerCase() === seen) {
        ok(findings, code, `networkIdentity.${field} matches the chain: ${seen}`);
      } else {
        bad(
          findings,
          code,
          `${input.recordPath} networkIdentity.${field} is ${recorded} but the chain says ${seen}. ` +
            `Do not edit the record to agree with an endpoint you have not vetted: find out which is wrong.`,
        );
      }
    };
    compare("C8", "genesisHash", record.genesisHash, observed.genesisHash);
    compare("C9", "multicall3", record.multicall3, hasCode ? multicall3 : null);
  }

  const fragment =
    observed.genesisHash === null || !hasCode
      ? null
      : [
          `  "networkIdentity": {`,
          `    "genesisHash": "${observed.genesisHash}",`,
          `    "multicall3": "${multicall3}",`,
          `    "source": { "url": null, "date": "${input.today ?? todayUtc()}" }`,
          `  }`,
        ].join("\n");

  return {
    findings,
    observed,
    fragment,
    ok: findings.every((finding) => finding.level !== "error"),
  };
}

// ---------------------------------------------------------------------------
// Reporting and CLI
// ---------------------------------------------------------------------------

export function report(result: CheckResult, recordPath: string): string {
  const lines: string[] = [];
  for (const finding of result.findings) {
    const status = finding.level === "error" ? "FAIL" : finding.level === "note" ? "note" : "ok  ";
    lines.push(`${status}  ${finding.code}  ${finding.message}`);
  }
  lines.push("");
  if (result.fragment === null) {
    lines.push("No fragment: the chain did not answer the two facts the record holds.");
  } else if (result.ok) {
    lines.push(`Paste into ${recordPath}, replacing the whole "networkIdentity" object:`);
    lines.push("");
    lines.push(result.fragment);
    lines.push("");
    lines.push(
      'Set "source".url to the page the Multicall3 address came from, keep the date, then run ' +
        "`npx pnpm@12.3.4 validate:config`. This script does not write the file.",
    );
  } else {
    lines.push("Something above failed. The fragment is withheld; fix the failure and run this again.");
  }
  return lines.join("\n");
}

type Args = {rpcUrl: string; chainId: bigint; multicall3: string; configRoot: string; headSlack?: bigint};

export class UsageError extends Error {}

export const USAGE =
  "usage: node scripts/check_chain_record.ts --rpc-url <url> --chain-id <id> --multicall3 <address>\n" +
  "                                          [--config-root <dir>] [--head-slack <blocks>]";

export function parseArgs(argv: readonly string[]): Args {
  const values = new Map<string, string>();
  for (let i = 0; i < argv.length; i += 1) {
    const flag = argv[i];
    if (flag === "--write" || flag === "--fix" || flag === "--apply") {
      throw new UsageError(
        `${flag} is refused: this script is read-only. It prints the fragment and you paste it, so that ` +
          "no configuration record is ever changed by an endpoint's answer.",
      );
    }
    if (!flag.startsWith("--")) throw new UsageError(`unexpected argument ${JSON.stringify(flag)}`);
    const next = argv[i + 1];
    if (next === undefined || next.startsWith("--")) throw new UsageError(`${flag} needs a value`);
    values.set(flag, next);
    i += 1;
  }
  const required = (flag: string): string => {
    const value = values.get(flag);
    if (value === undefined || value.trim() === "") throw new UsageError(`${flag} is required`);
    return value.trim();
  };
  const rpcUrl = required("--rpc-url");
  if (!/^https?:\/\//.test(rpcUrl)) throw new UsageError("--rpc-url must be an http(s) URL");
  const chainIdText = required("--chain-id");
  if (!/^[0-9]+$/.test(chainIdText)) throw new UsageError("--chain-id must be a positive integer");
  const chainId = BigInt(chainIdText);
  if (chainId <= 0n) throw new UsageError("--chain-id must be a positive integer");
  const multicall3 = required("--multicall3");
  if (!ADDRESS_RE.test(multicall3)) {
    throw new UsageError("--multicall3 must be an 0x-prefixed 20-byte address");
  }
  const slackText = values.get("--head-slack");
  if (slackText !== undefined && !/^[0-9]+$/.test(slackText)) {
    throw new UsageError("--head-slack must be a non-negative integer");
  }
  return {
    rpcUrl,
    chainId,
    multicall3,
    configRoot: values.get("--config-root")?.trim() || join(REPO_ROOT, "config"),
    headSlack: slackText === undefined ? undefined : BigInt(slackText),
  };
}

/** Reads the two `networkIdentity` fields, or null when the record is absent. */
export function loadRecord(path: string): ChainRecordIdentity | null {
  let raw: string;
  try {
    raw = readFileSync(path, "utf8");
  } catch {
    return null;
  }
  const doc = JSON.parse(raw) as Record<string, unknown>;
  const identity = doc.networkIdentity;
  const field = (name: string): string | null => {
    if (identity === null || typeof identity !== "object") return null;
    const value = (identity as Record<string, unknown>)[name];
    return typeof value === "string" ? value : null;
  };
  return {
    chainId: typeof doc.chainId === "number" ? doc.chainId : null,
    genesisHash: field("genesisHash"),
    multicall3: field("multicall3"),
  };
}

async function main(): Promise<void> {
  let args: Args;
  try {
    args = parseArgs(process.argv.slice(2));
  } catch (error) {
    process.stderr.write(`${error instanceof UsageError ? error.message : String(error)}\n${USAGE}\n`);
    process.exitCode = 2;
    return;
  }
  const recordPath = resolve(args.configRoot, "chains", `${args.chainId}.json`);
  const display = `config/chains/${args.chainId}.json`;
  process.stdout.write(
    `Reading chain ${args.chainId} through <rpc>, Multicall3 at ${args.multicall3.toLowerCase()}.\n\n`,
  );
  const result = await checkChainRecord({
    chainId: args.chainId,
    multicall3: args.multicall3,
    rpc: httpRpc(args.rpcUrl),
    record: loadRecord(recordPath),
    recordPath: display,
    headSlack: args.headSlack,
  });
  process.stdout.write(`${report(result, display)}\n`);
  process.exitCode = result.ok ? 0 : 1;
}

if (process.argv[1] !== undefined && pathToFileURL(process.argv[1]).href === import.meta.url) {
  await main();
}
